"""deduplicate weekly_plans and add unique constraint

Revision ID: 18260a3e72e0
Revises: 7bf0eb6f1bbf
Create Date: 2026-03-02 18:14:41.893825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18260a3e72e0'
down_revision: Union[str, Sequence[str], None] = '7bf0eb6f1bbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Delete orphaned planned_sessions for duplicate plans (keep latest per user+week)
    op.execute(
        """
        DELETE FROM planned_sessions
        WHERE plan_id IN (
            SELECT wp.id FROM weekly_plans wp
            WHERE wp.id NOT IN (
                SELECT id FROM (
                    SELECT id, ROW_NUMBER() OVER (
                        PARTITION BY user_id, week_start
                        ORDER BY created_at DESC
                    ) AS rn
                    FROM weekly_plans
                ) ranked
                WHERE rn = 1
            )
        )
        """
    )
    # Delete duplicate weekly_plans, keeping only the latest per user+week
    op.execute(
        """
        DELETE FROM weekly_plans
        WHERE id NOT IN (
            SELECT id FROM (
                SELECT id, ROW_NUMBER() OVER (
                    PARTITION BY user_id, week_start
                    ORDER BY created_at DESC
                ) AS rn
                FROM weekly_plans
            ) ranked
            WHERE rn = 1
        )
        """
    )

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_plans', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_weekly_plans_user_week', ['user_id', 'week_start'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_plans', schema=None) as batch_op:
        batch_op.drop_constraint('uq_weekly_plans_user_week', type_='unique')

    # ### end Alembic commands ###
