"""add email preference columns to users

Revision ID: 34197c0b4014
Revises: fcd0027ecc60
Create Date: 2026-02-15 23:44:31.773156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34197c0b4014'
down_revision: Union[str, Sequence[str], None] = 'fcd0027ecc60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_daily_briefing', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('email_weekly_plan', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('email_post_workout', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('email_sleep_coaching', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('email_weekly_recap', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email_weekly_recap')
        batch_op.drop_column('email_sleep_coaching')
        batch_op.drop_column('email_post_workout')
        batch_op.drop_column('email_weekly_plan')
        batch_op.drop_column('email_daily_briefing')

    # ### end Alembic commands ###
