"""add swimming metrics columns

Revision ID: 745b7e4011b2
Revises: 18260a3e72e0
Create Date: 2026-03-03 08:38:03.446742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '745b7e4011b2'
down_revision: Union[str, Sequence[str], None] = '18260a3e72e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('moving_duration_seconds', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fastest_split_100_seconds', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('avg_strokes_per_length', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_column('avg_strokes_per_length')
        batch_op.drop_column('fastest_split_100_seconds')
        batch_op.drop_column('moving_duration_seconds')

    # ### end Alembic commands ###
