"""add distance speed raw_data to activities

Revision ID: 77bcfaf2e87c
Revises: 9889769a175e
Create Date: 2026-02-23 22:12:13.368496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77bcfaf2e87c'
down_revision: Union[str, Sequence[str], None] = '9889769a175e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('distance_meters', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('avg_speed_mps', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('raw_data', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_column('raw_data')
        batch_op.drop_column('avg_speed_mps')
        batch_op.drop_column('distance_meters')

    # ### end Alembic commands ###
