"""add new health and activity metrics columns

Revision ID: 7bf0eb6f1bbf
Revises: cf66f22e4752
Create Date: 2026-02-26 18:20:52.786908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bf0eb6f1bbf'
down_revision: Union[str, Sequence[str], None] = 'cf66f22e4752'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('epoc', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('recovery_time_minutes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('avg_cadence', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('avg_swolf', sa.Float(), nullable=True))

    with op.batch_alter_table('daily_health_snapshots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hrv_status_text', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('body_battery_morning', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('recovery_time_hours', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('load_focus', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_health_snapshots', schema=None) as batch_op:
        batch_op.drop_column('load_focus')
        batch_op.drop_column('recovery_time_hours')
        batch_op.drop_column('body_battery_morning')
        batch_op.drop_column('hrv_status_text')

    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_column('avg_swolf')
        batch_op.drop_column('avg_cadence')
        batch_op.drop_column('recovery_time_minutes')
        batch_op.drop_column('epoc')

    # ### end Alembic commands ###
