"""make routine_days day_of_week nullable

Revision ID: 9889769a175e
Revises: b66448d822d1
Create Date: 2026-02-23 16:58:35.339987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9889769a175e'
down_revision: Union[str, Sequence[str], None] = 'b66448d822d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routine_days', schema=None) as batch_op:
        batch_op.alter_column('day_of_week',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routine_days', schema=None) as batch_op:
        batch_op.alter_column('day_of_week',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
