"""add superset_group to routine_exercises

Revision ID: b66448d822d1
Revises: 743e264deef9
Create Date: 2026-02-23 15:39:47.506719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b66448d822d1'
down_revision: Union[str, Sequence[str], None] = '743e264deef9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routine_exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('superset_group', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routine_exercises', schema=None) as batch_op:
        batch_op.drop_column('superset_group')

    # ### end Alembic commands ###
