"""remove_start_time_duration_from_weekly_availabilities

Revision ID: cf66f22e4752
Revises: d4e5f6a7b8c9
Create Date: 2026-02-26 18:30:30.598057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf66f22e4752'
down_revision: Union[str, Sequence[str], None] = 'd4e5f6a7b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_availabilities', schema=None) as batch_op:
        batch_op.drop_column('start_time')
        batch_op.drop_column('duration_minutes')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_availabilities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration_minutes', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('start_time', sa.TIME(), nullable=False))

    # ### end Alembic commands ###
